### ISSUE TITLE
RimSort does not work with LocalMods

### ISSUE THREAD

**Issue by ezadEzanee** [oceancabbage/RimSort#49]
Good day,

I've recently made copies of my mods locally. Prior to that everything works fine and as expected with Steam version mods. As shown on the sceenshot below, RimSort does not recognized dependant mods eventhough it is loaded in the list.

![Screen Shot 2023-03-26 at 06 39 45 AM](https://user-images.githubusercontent.com/18095325/227745684-c8d0e5df-a274-4520-81e1-edb45fb59eec.png)

**Comment by ezadEzanee** [comment]
It seems that out of 500ish mods I have, only a handful of them had this bug where Rimworld is looking for the dependency though the local copy is there and consistent in size and number of files. Can only fix that by loading the Steam version.

Btw I saw version 1.3 was released today. When will you release the Mac version? Many thanks.

**Comment by oceancabbage** [comment]
Hi @ezadEzanee, sorry for the delay in getting back to you. I tried to recreate your issue on my end-- here's what I did:

1. Fresh install of RimWorld with no local mods and 30-ish steam mods (some mods depend on other mods in this list).
2. Go to the Workshop mods folder and move all of the mods here to the Local mods folder.
3. Refresh the client and now all the 30-ish mods are local mods.
4. Click sort to sort all the mods.
5. Observe the results.

Doing the steps above, I don't see a difference for the load order _or_ the number of warnings _or_ which mods are missing which dependencies between all the mods being from steam and all the mods being local. See the attached screenshots below. (basically I wasn't able to reproduce your issue)

I _am_ running the Alpha 1.0.3 version though, so maybe this issue was fixed recently. I've just now uploaded the 1.0.3 RC2 Mac Build, can you try doing the same thing, but with the new build (should be the Darwin zip)? https://github.com/oceancabbage/RimSort/releases/tag/alpha-v1.0.3-RC2

Let me know if the issue still persists! And thank you for submitting an issue letting us know about it :)

<img width="1195" alt="Screenshot 2023-03-29 at 1 06 23 AM" src="https://user-images.githubusercontent.com/124647538/228468171-4de18488-f28b-4733-8dcc-95d92fdd8a9d.png">

<img width="1202" alt="Screenshot 2023-03-29 at 1 05 46 AM" src="https://user-images.githubusercontent.com/124647538/228468036-eee97883-0860-4bba-903a-1a5e42877898.png">

**Comment by oceancabbage** [comment]
@ezadEzanee I went back and tried recreating the issue on the 1.0.2 release, but still wasn't able to get it. Maybe it's the mod list I'm using? If the problem still persists on 1.0.3, I'm interested in seeing your logs-- there might be a clue there to what's going wrong.

**Comment by ezadEzanee** [comment]
Good day @oceancabbage, many thanks for the reply. What differs between the steps that you took to reproduce the error and what I did was on porting the mods from Steam to Local. I used Mod Manager back then. I tried again using your steps everything works as mentioned.

Something new I learned today - apps written on Darwin runs on Mac.
